### ISSUE TITLE
Update broke the modpack completely

### ISSUE THREAD

**Issue by NakedGranny** [Sketaful/Sketaful-s-Valheim-Adventure-Modpack#1]
Days ago just before the update on the 14th, I was playing on your server just fine. Yesterday and today the 17th, though, trying to load into the game shows a bunch of errors in the loading log and game crashes before loading to menu. It seems the 218.15 Ashlands patch broke everything (there's chatter that it's broken a lot of others' stuff too).

Main complaint about the actual content of the modpack is that the biomes are **FAR** too densely cluttered with garbage, to the point that it literally makes it difficult to just *move* through the world. You have to constantly be jumping just so you don't get caught and stuck on some random "plant". Half of the clutter you can move through, and the other half you can't. But you can't see anything because of how much garbage is on the screen (on top of the useless Valheim torches not illuminating anything while their awful bloom flare obscure your vision even of yourself while at night). Basically the game becomes a pitch black square at night while the biomes are not even navigable during the day just because it's random chance whether that shrub will block your movement... and there's something in the way literally every half meter. The Black Forest you literally cannot even walk, you *HAVE TO* jump every single step in order to move.

And then there's the insanity of four-purple-star greylings and boars swarming the Meadow even when you first spawn in. Random greylings are often literally tankier and deadlier than Eikthyr. And they *will* chase you forever. I ran from one end of the starting continent all the way around the perimeter of the shoreline, and all the way back to the spawn point with the same boar chasing me the whole way. Absolutely unacceptable. Server population is not nearly dense enough for every trash mob to be a raid encounter. That bullshit is obnoxious and needs to be reverted back to vanilla.

**Comment by NakedGranny** [comment]
Update:
The version of the modpack uploaded to Thundertree about an hour ago has not resolved issues - in fact, it seems to include the wrong versions of component mods entirely. Attempting to load into the server now takes a few minutes before it boots you back out to the game's main menu with a message that you need to downgrade your game's version and the versions of multiple mods.

**Comment by Sketaful** [comment]
To the first part.
I never updated the modpacks to the Ashland update so you had to downgrade
your valheim version to continue play.

Now I have updated. But it firmly says in the update info that I still
haven't updated the server. Only the modpack.

The reason I haven't updated the server yet is also explained in the update
info.
The server is a physical server at my home. Today I'm putting everything in
my apartment into boxes and tomorrow I'm moving to a new apartment so the
server will be turned of during this time. Updating the server before I've
moved is no use since I need the time to pack and the server won't be
online again until the middle of next week when my Internet have been moved
and I have unpacked everything.

Sorry about that, but that's how I have to do it atm.

It does however in the modpacks update say that I have removed the clutter
because it agree, it was awful.
On the server it will still be a lot of clutter but only in areas that's
been explored. New areas will only contain new trees, not any flowers,
grass, bushes and other things pretty useless. I've also made the amount of
new trees less.

So when the server is updated and up new explored areas will be a lot
better (I hope).

Try the modpack on a new single player map and you'll see the difference in
clutter. ;)

And please. Always read the update info on the page. It will often tell you
if there is something special with the update.

Take care.

Den lör 18 maj 2024 13:35NakedGranny ***@***.***> skrev:

**Comment by Sketaful** [comment]
Also. About the stars on the mobs. Yes, I know. They're difficult. They're easy as hell as soon as you get some gear, even the early gear (stone sword etc). But before that they're hard.

This is because the server add a higher chance of stars on the mobs based on the time of the world and the server have been online for quite a while.

I am going to add in some configs to make new characters start with some basic equipment to remedy this, but until that use your torch. Animals and greylings are afraid of fire. Picking up a torch in your hand when they get close will stop them from hitting you and try to run away. Hit them before they have run away and then put down your torch to make them come to you again and repeat until they're dead is my advice.

I never found greylings difficult, even with 4 stars since their attacks are easily dodged. But I hated the foxes at the start. ;p

**Comment by NakedGranny** [comment]
Scaling mobs based on uptime of the world is... not really logical. As you can see, new players are suddenly confronted with epic raid bosses that one-shot them frequently. During the first ten minutes of trying out your server. It arbitrarily punishes new players very harshly in a way they have no realistic counterplay for. And handing them equipment to start with isn't an elegant solution since that equipment will need to get better over time (and you'll probably have to manually adjust that periodically) as mobs continue to scale. In other words, you're creating a treadmill that you as the world designer have to manually keep up with, instead of just leaving mob scaling alone... or better yet, scaling them based on the progression / ability of the players in the area when the mob is spawned. Players form an impression about your server in those first ten minutes. Getting one-shot by a fox zooming up to spawn camp you at the world origin is *not* the look you want to go for. And making crucially-important mobs raid targets is also not functional on a low-population private server. If you had hundreds of people around so you could have a group to help kill trolls or whatever, that'd be different. 

Having to periodically beg players for help to just do basic progression and essential tasks? Hoping that someone can stop what they're doing to spend fifteen minutes traveling from the other side of the world - if there is a route for them to do so in the first place? Absolutely **hard** no from me. I don't care if it's one of the extremely few servers that makes magic available.

It's true I could just run it all single player mode.

...

We could **all** just play in single-player mode...

**Comment by Sketaful** [comment]
When I said to try it single player mode I meant if you wanted to check out
how the clutter is gone, since you can't check that out on the server when
it's not updated yet.

But sure, you can play it single player, sure everyone can play it single
player.

The server will be updated and I'll look into it based on time I have.
Something should be able to be done. I don't want it removed entirely
because it actually works very well with how much powerful you as a player
become as you progress.

Basic equipment at start is one idea. You say it will need to be upped from
time to time as the mobs get harder but, no, not really. They don't become
that much harder and they have a limit on how hard they can get.

But I'll look into it. Some changes shouldn't be impossible.

I do however state on the modpage that the server is for me trying out
things and that everyone's welcome but it isn't a "serious server" so it's
for everyone but it's mostly used by me and some friends mainly to try out
how the mods work on a server. Since then quite a bunch of people have
actually joined in from time to time so I guess I need to do a rework of
the starting area to make it a bit more forgiving.

Den lör 18 maj 2024 15:41NakedGranny ***@***.***> skrev:
