### ISSUE TITLE
Failing to Load Properly

### ISSUE THREAD

**Issue by anhuevo** [Sketaful/Sketaful-s-Valheim-Adventure-Modpack#3]
Recently tried getting back into Valheim and found your pack, and decided to try it out, but I've gotten nothing but the $menu_ + error log spam that caused me to give up on my last attempt at modding Valheim.

**Comment by Sketaful** [comment]
What launcher did you use?
What version of the modpacks did you use?

I've just been through fixing some problems with the modpack since the Ashland update and trying put the last version seemed to work fine for me, even though I haven't had time to test it fully yet since I also needed to sleep.

The menu log spam is new though. Never gotten that before more than when the game got an update and the mods didn't. Shouldn't be a problem now but if it is I need a bit more info. Going to check the modpack again as well as soon as I've had my coffee. :)
