### ISSUE TITLE
Boss stones Disappeared

### ISSUE THREAD

**Issue by Void-180** [Sketaful/Sketaful-s-Valheim-Adventure-Modpack#5]
The boss standing stones vanished. were playing on the most up to date modpack for reference.
![image](https://github.com/Sketaful/Sketaful-s-Valheim-Adventure-Modpack/assets/172191946/5bab39b2-4c53-4689-b64d-2bf5ecddbf6f)

**Comment by Sketaful** [comment]
That's really weird. It happened to me on my server once when updating mods, But that was like more than 20 updates ago and never happened since.  
I never figured out what made them disappear, I wasn't even sure at the time that it wasn't ruined hy someone using a cheat. I guess it wasn't since you experienced the same thing now.

Do you have a logfile or something I could take a look at? Would really help. When it happened to me I ended up using dev-commands mod and infinity hammer mod to place them out myself again and that was it, since it never happened again.
